import React from 'react'
import { Document } from '@bdp-rps/react-pdf-renderer'

import Song from './Song'

const songs = [
  'abends',
  'abends-treten-elche-aus-den-duenen',
  'ach-liebes-sage-mir',
  'am-ural',
  'an-land',
  'andre-die-das-land-so-sehr-nicht-liebten',
  'auf-vielen-strassen-dieser-welt',
  'balkanlied',
  'ballade-von-der-gemeinsamen-zeit',
  'banner',
  'big-bomb-dolly',
  'black-is-the-colour',
  'bleib-stehn-alte-dampflock',
  'bobbys-fernweh',
  'both-sides-the-tweed',
  'buendische-vaganten',
  'buergerlied',
  'caje-ukarije',
  'daemmert-von-fern',
  'das-schiff-im-nebel',
  'das-stundenglas',
  'das-wochenlied',
  'der-alte-fahrtengaenger',
  'der-apfel',
  'der-kleine-troll',
  'der-pfahl',
  'der-rabe',
  'der-raschler',
  'der-tramper',
  'der-wagen',
  'der-zug',
  'die-backsteinmauer',
  'die-ballade-vom-roten-haar',
  'die-daemmerung-fllt',
  'die-drei-glaenzenden-kugeln',
  'die-freie-republik',
  'die-grenze',
  'die-horte-kommt',
  'die-klampfen-erklingen',
  'die-kraniche-fliegen-im-keil',
  'die-lappen-hoch',
  'die-moorsoldaten',
  'die-nussbraune-maid',
  'die-sandbank',
  'die-schlesischen-weber',
  'die-schluchten-des-balkans',
  'die-tippelei',
  'die-zunft-der-strassenbrueder',
  'diregelt',
  'dornen-und-steine',
  'dort-an-dem-ueferchen',
  'drei-rote-pfiffe',
  'drei-tropfen-blut',
  'drill-ye-terriers',
  'du-schoener-leichtfuss',
  'edelweisspiraten',
  'ein-hotdog-unten-am-hafen',
  'ein-junges-lied',
  'ein-krampenschlag-vor-tag',
  'ein-stolzes-schiff',
  'endlos-sind-jene-strassen',
  'es-fuehrt-ber-den-main',
  'es-war-an-einem-sommertag',
  'fahr-mein-kind',
  'fahrt-in-den-herbst',
  'fiddlers-green',
  'fruehlingslied',
  'geburtstagslied',
  'gori-kaseki',
  'gospodar',
  'gute-nacht-kameraden',
  'heute-hier-morgen-dort',
  'hoch-im-norden',
  'hochzeit',
  'humor',
  'hyazinthen',
  'i-gorgona',
  'ich-kenne-europas-zonen',
  'in-die-sonne-die-ferne-hinaus',
  'jalava',
  'jasmin',
  'jerchenkow',
  'kaffee-und-karin',
  'landrattenschar',
  'lasst-uns-singen',
  'leezie-lindsay',
  'lied-der-schmiede',
  'lilas-blanches',
  'lumpenbruederschaft',
  'lustig-lustig',
  'makedonsko-devojce',
  'man-sagt',
  'manchmal-des-nachts',
  'mker',
  'molly-malone',
  'mori-shej',
  'muro-shavo',
  'nacht-in-portugal',
  'nachtfahrt',
  'nachts-auf-dem-dorfplatz',
  'nane-tsocha',
  'nehmt-abschied-brueder',
  'nicht-nur-nebenbei',
  'nordwaerts',
  'nun-greift-in-die-saiten',
  'o-bootsmann',
  'ore-ore',
  'ostseewinter',
  'palzlied',
  'paporaki',
  'papst-und-sultan',
  'piet-am-galgen',
  'piratenbraut',
  'piratenhafen',
  'piratenlied',
  'raubritter',
  'regen-regen',
  'regenbogenlied',
  'ride-on',
  'roter-mond',
  'roter-wein-im-becher',
  'santiano',
  'sardegna',
  'schilf',
  'schlaflied-des-franzes',
  'schlaflied-fuer-anne',
  'schliess-aug-und-ohr',
  'schon-so-lang',
  'seemannsmaetresse',
  'sonnenschein-und-wilde-feste',
  'steuermann-ho',
  'stunde-der-orangen',
  'sturm-und-drang',
  'tanzlied-der-spielleute',
  'tanzlied-des-totenschiffes',
  'ten-thousand-miles-away',
  'the-black-and-tans',
  'the-colliery-gate',
  'the-road',
  'tod-und-mediziner',
  'tommi',
  'trinklied-vorm-abgang',
  'triodimali',
  'tschiree',
  'tsen-brider',
  'tumbalalaika',
  'ulanen',
  'und-ob-der-sturm',
  'ungarische-hochzeit',
  'unter-dem-pflaster',
  'unter-den-toren',
  'viva-la-feria',
  'walk-with-the-wind',
  'warum-zoegerst-du-noch',
  'was-helfen-mir-tausend-dukaten',
  'was-uns-laesst-fahren',
  'welle-wogte',
  'wenn-das-feuer-hell-und-heiss',
  'wenn-der-abend-naht',
  'wenn-der-fruehling-kommt',
  'wenn-die-buerger-schlafen-gehn',
  'wenn-hell-die-goldne-sonne-lacht',
  'westwaerts',
  'wilde-reiter',
  'winterlied',
  'wir-drei-wir-gehn-jetzt-auf-die-walze',
  'wir-kamen-einst-von-piemont',
  'wir-sind-die-rheinischen-vandalen',
  'wir-sind-eine-kleine-verloren-schar',
  'wir-zogen-in-das-feld',
  'wos-nur-felsen-gibt',
  'ye-jacobites',
  'ziehharmonika',
  'zug-der-schwaene',
  'zuhause',
  'zum-nebel',
]

const songData = songs.map((song) => require('../songs/' + song + '.json'))

const normalizeContent = (content) =>
  content.replace(/{[a-z0-9]}/gi, '').toLowerCase()

export default () => (
  <Document>
    {songData
      .sort((a, b) => {
        const tA = normalizeContent(a.content)
        const tB = normalizeContent(b.content)

        return tA > tB ? 1 : -1
      })
      .map((data) => (
        <Song key={data.title} {...data} />
      ))}
  </Document>
)
